COUNTRIES = {
    "United States": "+1",
    "United Kingdom": "+44",
    "Afghanistan (‫افغانستان‬‎)": "+93",
    "Albania (Shqipëri)": "+355",
    "Algeria (‫الجزائر‬‎)": "+213",
    "American Samoa": "+1684",
    "Andorra": "+376",
    "Angola": "+244",
    "Anguilla": "+1264",
    "Antigua and Barbuda": "+1268",
    "Argentina": "+54",
    "Armenia (Հայաստան)": "+374",
    "Aruba": "+297",
    "Australia": "+61",
    "Austria (Österreich)": "+43",
    "Azerbaijan (Azərbaycan)": "+994",
    "Bahamas": "+1242",
    "Bahrain (‫البحرين‬‎)": "+973",
    "Bangladesh (বাংলাদেশ)": "+880",
    "Barbados": "+1246",
    "Belarus (Беларусь)": "+375",
    "Belgium (België)": "+32",
    "Belize": "+501",
    "Benin (Bénin)": "+229",
    "Bermuda": "+1441",
    "Bhutan (འབྲུག)": "+975",
    "Bolivia": "+591",
    "Bosnia and Herzegovina (Босна и Херцеговина)": "+387",
    "Botswana": "+267",
    "Brazil (Brasil)": "+55",
    "British Indian Ocean Territory": "+246",
    "British Virgin Islands": "+1284",
    "Brunei": "+673",
    "Bulgaria (България)": "+359",
    "Burkina Faso": "+226",
    "Burundi (Uburundi)": "+257",
    "Cambodia (កម្ពុជា)": "+855",
    "Cameroon (Cameroun)": "+237",
    "Canada": "+1",
    "Cape Verde (Kabu Verdi)": "+238",
    "Caribbean Netherlands": "+599",
    "Cayman Islands": "+1345",
    "Central African Republic (République centrafricaine)": "+236",
    "Chad (Tchad)": "+235",
    "Chile": "+56",
    "China (中国)": "+86",
    "Christmas Island": "+61",
    "Cocos (Keeling) Islands": "+61",
    "Colombia": "+57",
    "Comoros (‫جزر القمر‬‎)": "+269",
    "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)": "+243",
    "Congo (Republic) (Congo-Brazzaville)": "+242",
    "Cook Islands": "+682",
    "Costa Rica": "+506",
    "Côte d’Ivoire": "+225",
    "Croatia (Hrvatska)": "+385",
    "Cuba": "+53",
    "Curaçao": "+599",
    "Cyprus (Κύπρος)": "+357",
    "Czech Republic (Česká republika)": "+420",
    "Denmark (Danmark)": "+45",
    "Djibouti": "+253",
    "Dominica": "+1767",
    "Dominican Republic (República Dominicana)": "+1",
    "Ecuador": "+593",
    "Egypt (‫مصر‬‎)": "+20",
    "El Salvador": "+503",
    "Equatorial Guinea (Guinea Ecuatorial)": "+240",
    "Eritrea": "+291",
    "Estonia (Eesti)": "+372",
    "Ethiopia": "+251",
    "Falkland Islands (Islas Malvinas)": "+500",
    "Faroe Islands (Føroyar)": "+298",
    "Fiji": "+679",
    "Finland (Suomi)": "+358",
    "France": "+33",
    "French Guiana (Guyane française)": "+594",
    "French Polynesia (Polynésie française)": "+689",
    "Gabon": "+241",
    "Gambia": "+220",
    "Georgia (საქართველო)": "+995",
    "Germany (Deutschland)": "+49",
    "Ghana (Gaana)": "+233",
    "Gibraltar": "+350",
    "Greece (Ελλάδα)": "+30",
    "Greenland (Kalaallit Nunaat)": "+299",
    "Grenada": "+1473",
    "Guadeloupe": "+590",
    "Guam": "+1671",
    "Guatemala": "+502",
    "Guernsey": "+44",
    "Guinea (Guinée)": "+224",
    "Guinea-Bissau (Guiné Bissau)": "+245",
    "Guyana": "+592",
    "Haiti": "+509",
    "Honduras": "+504",
    "Hong Kong (香港)": "+852",
    "Hungary (Magyarország)": "+36",
    "Iceland (Ísland)": "+354",
    "India (भारत)": "+91",
    "Indonesia": "+62",
    "Iran (‫ایران‬‎)": "+98",
    "Iraq (‫العراق‬‎)": "+964",
    "Ireland": "+353",
    "Isle of Man": "+44",
    "Israel (‫ישראל‬‎)": "+972",
    "Italy (Italia)": "+39",
    "Jamaica": "+1",
    "Japan (日本)": "+81",
    "Jersey": "+44",
    "Jordan (‫الأردن‬‎)": "+962",
    "Kazakhstan (Казахстан)": "+7",
    "Kenya": "+254",
    "Kiribati": "+686",
    "Kosovo": "+383",
    "Kuwait (‫الكويت‬‎)": "+965",
    "Kyrgyzstan (Кыргызстан)": "+996",
    "Laos (ລາວ)": "+856",
    "Latvia (Latvija)": "+371",
    "Lebanon (‫لبنان‬‎)": "+961",
    "Lesotho": "+266",
    "Liberia": "+231",
    "Libya (‫ليبيا‬‎)": "+218",
    "Liechtenstein": "+423",
    "Lithuania (Lietuva)": "+370",
    "Luxembourg": "+352",
    "Macau (澳門)": "+853",
    "Macedonia (FYROM) (Македонија)": "+389",
    "Madagascar (Madagasikara)": "+261",
    "Malawi": "+265",
    "Malaysia": "+60",
    "Maldives": "+960",
    "Mali": "+223",
    "Malta": "+356",
    "Marshall Islands": "+692",
    "Martinique": "+596",
    "Mauritania (‫موريتانيا‬‎)": "+222",
    "Mauritius (Moris)": "+230",
    "Mayotte": "+262",
    "Mexico (México)": "+52",
    "Micronesia": "+691",
    "Moldova (Republica Moldova)": "+373",
    "Monaco": "+377",
    "Mongolia (Монгол)": "+976",
    "Montenegro (Crna Gora)": "+382",
    "Montserrat": "+1664",
    "Morocco (‫المغرب‬‎)": "+212",
    "Mozambique (Moçambique)": "+258",
    "Myanmar (Burma) (မြန်မာ)": "+95",
    "Namibia (Namibië)": "+264",
    "Nauru": "+674",
    "Nepal (नेपाल)": "+977",
    "Netherlands (Nederland)": "+31",
    "New Caledonia (Nouvelle-Calédonie)": "+687",
    "New Zealand": "+64",
    "Nicaragua": "+505",
    "Niger (Nijar)": "+227",
    "Nigeria": "+234",
    "Niue": "+683",
    "Norfolk Island": "+672",
    "North Korea (조선 민주주의 인민 공화국)": "+850",
    "Northern Mariana Islands": "+1670",
    "Norway (Norge)": "+47",
    "Oman (‫عُمان‬‎)": "+968",
    "Pakistan (‫پاکستان‬‎)": "+92",
    "Palau": "+680",
    "Palestine (‫فلسطين‬‎)": "+970",
    "Panama (Panamá)": "+507",
    "Papua New Guinea": "+675",
    "Paraguay": "+595",
    "Peru (Perú)": "+51",
    "Philippines": "+63",
    "Poland (Polska)": "+48",
    "Portugal": "+351",
    "Puerto Rico": "+1",
    "Qatar (‫قطر‬‎)": "+974",
    "Réunion (La Réunion)": "+262",
    "Romania (România)": "+40",
    "Russia (Россия)": "+7",
    "Rwanda": "+250",
    "Saint Barthélemy": "+590",
    "Saint Helena": "+290",
    "Saint Kitts and Nevis": "+1869",
    "Saint Lucia": "+1758",
    "Saint Martin (Saint-Martin (partie française))": "+590",
    "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)": "+508",
    "Saint Vincent and the Grenadines": "+1784",
    "Samoa": "+685",
    "San Marino": "+378",
    "São Tomé and Príncipe (São Tomé e Príncipe)": "+239",
    "Saudi Arabia (‫المملكة العربية السعودية‬‎)": "+966",
    "Senegal (Sénégal)": "+221",
    "Serbia (Србија)": "+381",
    "Seychelles": "+248",
    "Sierra Leone": "+232",
    "Singapore": "+65",
    "Sint Maarten": "+1721",
    "Slovakia (Slovensko)": "+421",
    "Slovenia (Slovenija)": "+386",
    "Solomon Islands": "+677",
    "Somalia (Soomaaliya)": "+252",
    "South Africa": "+27",
    "South Korea (대한민국)": "+82",
    "South Sudan (‫جنوب السودان‬‎)": "+211",
    "Spain (España)": "+34",
    "Sri Lanka (ශ්‍රී ලංකාව)": "+94",
    "Sudan (‫السودان‬‎)": "+249",
    "Suriname": "+597",
    "Svalbard and Jan Mayen": "+47",
    "Swaziland": "+268",
    "Sweden (Sverige)": "+46",
    "Switzerland (Schweiz)": "+41",
    "Syria (‫سوريا‬‎)": "+963",
    "Taiwan (台灣)": "+886",
    "Tajikistan": "+992",
    "Tanzania": "+255",
    "Thailand (ไทย)": "+66",
    "Timor-Leste": "+670",
    "Togo": "+228",
    "Tokelau": "+690",
    "Tonga": "+676",
    "Trinidad and Tobago": "+1868",
    "Tunisia (‫تونس‬‎)": "+216",
    "Turkey (Türkiye)": "+90",
    "Turkmenistan": "+993",
    "Turks and Caicos Islands": "+1649",
    "Tuvalu": "+688",
    "U.S. Virgin Islands": "+1340",
    "Uganda": "+256",
    "Ukraine (Україна)": "+380",
    "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)": "+971",
    "Uruguay": "+598",
    "Uzbekistan (Oʻzbekiston)": "+998",
    "Vanuatu": "+678",
    "Vatican City (Città del Vaticano)": "+39",
    "Venezuela": "+58",
    "Vietnam (Việt Nam)": "+84",
    "Wallis and Futuna (Wallis-et-Futuna)": "+681",
    "Western Sahara (‫الصحراء الغربية‬‎)": "+212",
    "Yemen (‫اليمن‬‎)": "+967",
    "Zambia": "+260",
    "Zimbabwe": "+263",
    "Åland Islands": "+358"
}
UNIVERSIDADES = [
    "Columbus University",
    "EAFIT",
    "Escuela de Arquitectura y Diseño de America Latina y el Caribe",
    "Florida State University",
    "INCAE - Business School",
    "International University (INTERUNI)",
    "ISAE - Campus Central - Ciudad de Panamá",
    "ISAE - Changuinola, Bocas del Toro",
    "ISAE - Chitré, Herrera",
    "ISAE - David, Chiriquí",
    "ISAE - La Chorrera, Pmá Oeste",
    "ISAE - Metetí, Darién",
    "ISAE - Penonomé, Coclé",
    "ISAE - Santiago, Veraguas",
    "ISTHMUS",
    "No estudiando actualmente - Chiriqui",
    "No estudiando actualmente - Coclé",
    "No estudiando actualmente - UDI",
    "No estudiando actualmente - Universidad de Panamá",
    "No estudiando actualmente - USMA",
    "No estudiando actualmente - UTP",
    "No estudiando actualmente - Veraguas",
    "Otro",
    "QLU Panama - University of Louisville",
    "UDELAS - Azuero",
    "UDELAS - Campus Ciudad de Panamá",
    "UDELAS - Chiriquí",
    "UDELAS - Coclé",
    "UDELAS - Colón",
    "UDELAS - Sede Veraguas",
    "UDELAS - Veraguas",
    "UDI Universidad del Istmo - Campus Ciudad de Panamá",
    "UDI Universidad del Istmo - Changuinola",
    "UDI Universidad del Istmo - Chiriquí",
    "UDI Universidad del Istmo - Chitré",
    "UDI Universidad del Istmo - Chorrera",
    "UDI Universidad del Istmo - Colón",
    "UDI Universidad del Istmo - Las Tablas",
    "UDI Universidad del Istmo - Los Pueblos",
    "UDI Universidad del Istmo - Panamá",
    "UDI Universidad del Istmo - Sede Veraguas",
    "ULACEX",
    "UMECIT",
    "Universidad Abierta y a Distancia - Sede Ciudad de Panamá",
    "Universidad Abierta y a Distancia - Sede Penonomé",
    "Universidad Abierta y a Distancia - Sede Santiago",
    "Universidad Americana - Campus Ciudad de Panamá",
    "Universidad Americana - El Carmen",
    "Universidad Americana - Los Pueblos",
    "Universidad Americana - Pmá. Oeste",
    "Universidad Autonoma de Chiriquí (UNACHI)",
    "Universidad Cristiana de Panamá",
    "Universidad de Alta Dirección",
    "Universidad de Cartago",
    "Universidad del Arte Ganexa",
    "Universidad de Panamá - Azuero",
    "Universidad de Panamá - Bocas del Toro",
    "Universidad de Panamá | Centro Regional de Azuero",
    "Universidad de Panamá - Coclé",
    "Universidad de Panamá - Colón",
    "Universidad de Panamá - Darién",
    "Universidad de Panamá - Los Santos",
    "Universidad de Panamá - Panamá Este",
    "Universidad de Panamá - Panamá Oeste",
    "Universidad de Panamá - San Miguelito",
    "Universidad de Panamá - Sede Ciudad de Panamá",
    "Universidad de Panamá - Veraguas",
    "Universidad de San Francisco de Panamá",
    "Universidad Hispoamericana de Panamá",
    "Universidad Interamericana de Panamá (UIP)",
    "Universidad Internacional de Ciencia y Tecnología UNICYT",
    "Universidad Latina - Chiriquí",
    "Universidad Latina - Chitré",
    "Universidad Latina de Panamá - Ciudad Capital",
    "Universidad Latina de Panamá - Sede Chitré",
    "Universidad Latina de Panamá - Sede Veraguas",
    "Universidad Latina - Fac. Ciencias de la Salud",
    "Universidad Latina - Penonomé",
    "Universidad Marítima Internacional de Panamá",
    "Universidad Panamericana (UPAM)",
    "Universidad Santander",
    "Universidad Tecnológica de Panamá - Azuero",
    "Universidad Tecnológica de Panamá - Bocas del Toro",
    "Universidad Tecnológica de Panamá - Chiriquí",
    "Universidad Tecnológica de Panamá - Coclé",
    "Universidad Tecnológica de Panamá - Colón",
    "Universidad Tecnológica de Panamá - Panamá Oeste",
    "Universidad Tecnológica de Panamá - Sede Ciudad de Panamá",
    "Universidad Tecnológica de Panamá - Sede Veraguas",
    "Universidad Tecnológica Oteima - Chiriquí",
    "Universidad Tecnológica Oteima - Santiago",
    "USMA - Campus Ciudad de Panamá",
    "USMA - Chiriquí",
    "USMA - Chitré",
    "USMA - Colón",
    "USMA - Sede Veraguas",""
]

""" LCs ID 
Dependiendo de la segmentacion checar pa que comite hay que enviar a la gente
UTP -> 193
Chriqui -> 2334
Balboa -> 2424
USMA -> 1473
COCLE -> 2453
UP -> 1949
SANTIAGO -> 1707
VE -> 2008
"""

"""Este diccionario posee las universidades, 
    su segmentacion y su ID de expa
"""
SEGMENTACION = {
    "Chiriquí": [
        [
            "Universidad Tecnológica de Panamá - Chiriquí",
            "No estudiando actualmente - Chiriqui",
            "Universidad de Panamá - Bocas del Toro",
            "Universidad Tecnológica de Panamá - Bocas del Toro",
            "UDELAS - Chiriquí",
            "UDI Universidad del Istmo - Changuinola",
            "USMA - Chiriquí",
            "Universidad Autonoma de Chiriquí (UNACHI)",
            "Universidad de Cartago",
            "UDI Universidad del Istmo - Chiriquí",
            "ISAE - Changuinola, Bocas del Toro",
            "ISAE - David, Chiriquí",
            "Universidad Latina - Chiriquí",
            "Universidad Tecnológica Oteima - Chiriquí"
        ],2334,5
    ],
    "Coclé": [
        [
            "Universidad de Panamá - Los Santos",
            "Universidad Latina - Chitré",
            "Universidad Abierta y a Distancia - Sede Penonomé",
            "No estudiando actualmente - Coclé",
            "Universidad Latina de Panamá - Sede Chitré",
            "UDI Universidad del Istmo - Chitré",
            "ISAE - Chitré, Herrera",
            "USMA - Chitré",
            "UDI Universidad del Istmo - Las Tablas",
            "UDELAS - Coclé",
            "Universidad de Panamá - Coclé",
            "Universidad Tecnológica de Panamá - Coclé",
            "ISAE - Penonomé, Coclé",
            "Universidad Latina - Penonomé"
        ],2453,3
    ],
    "Santiago": [
        [
            "UDI Universidad del Istmo - Sede Veraguas",
            "Universidad de Panamá - Azuero",
            "Universidad Tecnológica de Panamá - Sede Veraguas",
            "Universidad Abierta y a Distancia - Sede Santiago",
            "USMA - Sede Veraguas",
            "UDELAS - Sede Veraguas",
            "Universidad Latina de Panamá - Sede Veraguas",
            "Universidad de Panamá | Centro Regional de Azuero",
            "UDELAS - Azuero",
            "Universidad Tecnológica de Panamá - Azuero",
            "No estudiando actualmente - Veraguas",
            "Universidad Tecnológica Oteima - Santiago",
            "UDELAS - Veraguas",
            "ISAE - Santiago, Veraguas",
            "Universidad de Panamá - Veraguas"
        ],1707,4
    ],
    "UP": [
        [
            "QLU Panama - University of Louisville",
            "Universidad de Panamá - Panamá Oeste",
            "Universidad de Panamá - Colón",
            "Universidad de San Francisco de Panamá",
            "Universidad de Panamá - Panamá Este",
            "UDI Universidad del Istmo - Campus Ciudad de Panamá",
            "ISTHMUS",
            "No estudiando actualmente - UDI",
            "Universidad de Panamá - Sede Ciudad de Panamá",
            "UDI Universidad del Istmo - Panamá",
            "EAFIT",
            "Universidad Americana - Pmá. Oeste",
            "Universidad de Panamá - Darién",
            "UDELAS - Campus Ciudad de Panamá",
            "Florida State University",
            "UDI Universidad del Istmo - Los Pueblos",
            "Universidad Americana - Los Pueblos",
            "Columbus University",
            "No estudiando actualmente - Universidad de Panamá"
        ],1949,2
    ],
    "UTP": [
        [
            "Escuela de Arquitectura y Diseño de America Latina y el Caribe",
            "ISAE - Metetí, Darién",
            "UDI Universidad del Istmo - Chorrera",
            "ISAE - La Chorrera, Pmá Oeste",
            "Universidad de Panamá - San Miguelito",
            "USMA - Colón",
            "Universidad Santander",
            "Universidad Tecnológica de Panamá - Colón",
            "Universidad Americana - El Carmen",
            "Universidad Abierta y a Distancia - Sede Ciudad de Panamá",
            "UDELAS - Colón",
            "Universidad Americana - Campus Ciudad de Panamá",
            "Universidad Latina - Fac. Ciencias de la Salud",
            "International University (INTERUNI)",
            "Universidad Interamericana de Panamá (UIP)",
            "Universidad del Arte Ganexa",
            "UMECIT",
            "Universidad Latina de Panamá - Ciudad Capital",
            "ISAE - Campus Central - Ciudad de Panamá",
            "Universidad Tecnológica de Panamá - Panamá Oeste",
            "UDI Universidad del Istmo - Colón",
            "INCAE - Business School",
            "Universidad Hispoamericana de Panamá",
            "Universidad de Alta Dirección",
            "ADEN International Business School - Ciudad de Panamá",
            "Universidad Panamericana (UPAM)",
            "Universidad Marítima Internacional de Panamá",
            "Universidad Cristiana de Panamá",
            "Universidad Internacional de Ciencia y Tecnología UNICYT",
            "ULACEX",
            "No estudiando actualmente - USMA",
            "USMA - Campus Ciudad de Panamá",
            "No estudiando actualmente - UTP",
            "Universidad Tecnológica de Panamá - Sede Ciudad de Panamá"
            "Otro"
        ],193,1
    ],
    "VE":[["Otro"],2008,6]
}

""" EXPA REFERRALS WITH PODIO ID """
PODIO_REFERRAL = {
    "Friend":1,
    "Information booth on campus":2,
    "Classroom presentation":3,
    "Facebook":4,
    "WeChat":5,
    "Twitter":6,
    "Other social media channel":7,
    "Instagram":8,
    "LinkedIn":9,
    "Heading for the future":10,
    "Search engine":11,
    "Event": 12,
    "Emails":13,
    "Telegram":14,
    "Vk":15,
    "Media (magazine, TV, newspaper or radio)":16,
    "Other":17,
    "":1
}

PODIO_REFERENTES = {
    "Amig@":1,
    "Información en el campus":2,
    "Presentación en aula de clases":3,
    "Facebook":4,
    "Twitter":6,
    "Instagram":8,
    "LinkedIn":9,
    "Otra red social":7,
    "Motor de busqueda":11,
    "Evento": 12,
    "Emails":13,
    "Telegram":14,
    "Medios (Revista, TV, Periódico o radio)":16,
    "Otro":17,
    "":17
}


BACKGROUNDS = [
    "Accounting",
    "Aerospace engineering",
    "Agriculture",
    "Anthropology",
    "Archeology",
    "Architecture",
    "Arts",
    "Assurance",
    "Audit",
    "Automotive engineering",
    "Banking",
    "Bioengineering",
    "Biology",
    "Biomedical Science",
    "Business administration",
    "Chemical engineering",
    "Chemistry",
    "Civil engineering",
    "Communication & journalism",
    "Computer engineering",
    "Computer sciences",
    "Design",
    "Earth Sciences",
    "Ecology",
    "Economics",
    "Educación",
    "Electrical engineering",
    "Electronics engineering",
    "Entrepreneurship",
    "Environmental engineering",
    "Finance",
    "Geography",
    "Graphic design",
    "Health Science",
    "History",
    "Human Resources",
    "Industrial Design",
    "Industrial engineering",
    "International relations",
    "International Trade",
    "Idiomas",
    "Law",
    "Linguistics",
    "Literature",
    "Logística",
    "Marketing",
    "Material engineering",
    "Mathematics",
    "Mechanical engineering",
    "Media Arts",
    "Medicine",
    "Military sciences",
    "Music",
    "Nanotechnology",
    "Nursing",
    "Nutrition",
    "Petroleum Engineering",
    "Philosophy",
    "Physics",
    "Political science",
    "Psychology",
    "Public administration",
    "Public relations",
    "Religion",
    "Social Work",
    "Sociology",
    "Software development and programming",
    "Sports",
    "Statistics",
    "Systems and Computing Engineering",
    "Telecommunication Engineering",
    "Theatre",
    "Tourism & hotel management",
    "Veterinarian",
    "Other",
    ""
]

BACKGROUNDS_SPANISH = [
    "Contabilidad",
    "Ingeniería Aeroespacial",
    "Agricultura",
    "Antropología",
    "Arqueología",
    "Arquitectura",
    "Arte",
    "Seguros",
    "Auditorías",
    "Ingeniería automotriz",
    "Banca",
    "Bioingeniería",
    "Biología",
    "Ciencia Biomédica",
    "Administración de Empresas",
    "Ingeniería Química",
    "Química",
    "Ingeniería civil",
    "Comunicación y periodismo",
    "Ingeniería Informática",
    "Ciencias de la Computación",
    "Diseño",
    "Ciencias de la Tierra",
    "Ecología",
    "Ciencias económicas",
    "Educación",
    "Ingeniería eléctrica",
    "Ingeniería electrónica",
    "Emprendimiento",
    "Ingeniería Ambiental",
    "Finanzas",
    "Geografía",
    "Diseño gráfico",
    "Ciencia de la salud",
    "Historia",
    "Recursos humanos",
    "Diseño industrial",
    "Ingeniería Industrial",
    "Relaciones Internacionales",
    "Comercio internacional",
    "Idiomas",
    "Ley",
    "Lingüística",
    "Literatura",
    "Logística",
    "Marketing",
    "Ingeniería de materiales",
    "Matemáticas",
    "Ingeniería Mecánica",
    "Artes de los medios",
    "Medicina",
    "Ciencias militares",
    "Música",
    "Nanotecnología",
    "Enfermería",
    "Nutrición",
    "Ingeniería del Petróleo",
    "Filosofía",
    "Física",
    "Ciencias Políticas",
    "Psicología",
    "Administración Pública",
    "Relaciones públicas",
    "Religión",
    "Trabajo Social",
    "Sociología",
    "Ingeniería o Desarrollo de software",
    "Deportes",
    "Estadísticas",
    "Ingeniería en Sistemas y Computación",
    "Ingeniería en Telecomunicaciones",
    "Teatro",
    "Turismo y gestión hotelera",
    "Veterinaria",
    "Otro",
    ""]


NIVEL_INGLES = {
    "A1 - Principiante":1,
    "A2 - Elemental":2,
    "B1 - Intermedio":3,
    "B2 - Intermedio Alto":4,
    "C1 - Avanzado":5,
    "C2 - Nativo":6,
    "":1
}

ESTUDIOS =  {
    "Bachiller": 3,
    "Técnico": 4,
    "Pregrado (cursando)": 5,
    "Pregrado (graduado)": 6,
    "Postgrado": 7,
    "Doctorado/Maestria": 11,
    "":3
    }